src/main/java/de/jottyfan/camporganizer/CampBean.java
package de.jottyfan.camporganizer;

import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author jotty
 *
 */
public class CampBean {
	private Integer pk;
	private String name;
	private Integer fkLocation;
	private String locationName;
	private Integer year;
	private Integer minAge;
	private Integer maxAge;
	private String url;
	private Date arrive;
	private Date depart;
	private String price;
	private String countries;
	private Integer fkDocument;
	private Integer bookings;
	private Boolean lockSales;
	private Integer fkProfile;

	public String getFullCampname() {
		StringBuilder buf = new StringBuilder();
		buf.append(name).append(" ");
		buf.append(year).append(" in ");
		buf.append(locationName);
		return buf.toString();
	}

	public String getCampTime() {
		StringBuilder buf = new StringBuilder();
		buf.append(new SimpleDateFormat("E dd.MM.").format(arrive));
		buf.append(" - ");
		buf.append(new SimpleDateFormat("E dd.MM.yyyy").format(depart));
		return buf.toString();
	}

	public Integer getPk() {
		return pk;
	}

	public void setPk(Integer pk) {
		this.pk = pk;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getYear() {
		return year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}

	public String getLocationName() {
		return locationName;
	}

	public void setLocationName(String locationName) {
		this.locationName = locationName;
	}

	public Integer getMinAge() {
		return minAge;
	}

	public void setMinAge(Integer minAge) {
		this.minAge = minAge;
	}

	public Integer getMaxAge() {
		return maxAge;
	}

	public void setMaxAge(Integer maxAge) {
		this.maxAge = maxAge;
	}

	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public Date getArrive() {
		return arrive;
	}

	public void setArrive(Date arrive) {
		this.arrive = arrive;
	}

	public Date getDepart() {
		return depart;
	}

	public void setDepart(Date depart) {
		this.depart = depart;
	}

	public String getPrice() {
		return price;
	}

	public void setPrice(String price) {
		this.price = price;
	}

	public String getCountries() {
		return countries;
	}

	public void setCountries(String countries) {
		this.countries = countries;
	}

	public Integer getFkDocument() {
		return fkDocument;
	}

	public void setFkDocument(Integer fkDocument) {
		this.fkDocument = fkDocument;
	}

	public Integer getFkLocation() {
		return fkLocation;
	}

	public void setFkLocation(Integer fkLocation) {
		this.fkLocation = fkLocation;
	}

	public Integer getBookings() {
		return bookings;
	}

	public void setBookings(Integer bookings) {
		this.bookings = bookings;
	}

	public Boolean getLockSales() {
		return lockSales;
	}

	public void setLockSales(Boolean lockSales) {
		this.lockSales = lockSales;
	}

	public Integer getFkProfile() {
		return fkProfile;
	}

	public void setFkProfile(Integer fkProfile) {
		this.fkProfile = fkProfile;
	}
}

src/main/java/de/jottyfan/camporganizer/Controller.java
package de.jottyfan.camporganizer;

import java.io.IOException;
import java.io.OutputStream;
import java.util.Base64;

import javax.faces.application.FacesMessage;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;

import de.jottyfan.camporganizer.db.PersondocumentGateway;
import de.jottyfan.camporganizer.modules.subscriber.PersondocumentBean;

/**
 *
 * @author jotty
 *
 */
public abstract class Controller {
	public String toLogin() {
		return "/pages/login.jsf";
	}

	public String toProfile() {
		return "/pages/profile.jsf";
	}

	public String toRegister() {
		return "/pages/register.jsf";
	}

	/**
	 * download file encoded in base64
	 *
	 * @param contentBase64
	 * @param filetype
	 * @return empty string for an error
	 */
	public String doDownloadBase64(FacesContext facesContext, String contentBase64, String name, String filetype) {
		if (contentBase64 == null || contentBase64.isBlank()) {
			facesContext.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "error on downloading",
					"Das Dokument ist leer und enthält kein Daten."));
		} else {
			byte[] decodedContent = Base64.getDecoder().decode(contentBase64);
			ExternalContext ec = facesContext.getExternalContext();
			ec.responseReset();
			ec.setResponseContentType(filetype);
			ec.setResponseContentLength(decodedContent.length);
			ec.setResponseHeader("Content-Disposition", "attachment; filename=\"" + name + "." + filetype + "\"");
			try {
				OutputStream out = ec.getResponseOutputStream();
				out.write(decodedContent);
				out.flush();
				facesContext.responseComplete();
			} catch (IOException e) {
				facesContext.addMessage(null,
						new FacesMessage(FacesMessage.SEVERITY_ERROR, "error on downloading", e.getMessage()));
			}
		}
		return "";
	}
}

src/main/java/de/jottyfan/camporganizer/modules/businessman/SalesController.java
package de.jottyfan.camporganizer.modules.businessman;

import java.io.IOException;
import java.io.OutputStream;
import java.util.ArrayList;

import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.jooq.exception.DataAccessException;

import de.jottyfan.camporganizer.Controller;
import de.jottyfan.camporganizer.db.CampGateway;
import de.jottyfan.camporganizer.db.SalesGateway;
import de.jottyfan.camporganizer.db.jooq.enums.EnumModule;
import de.jottyfan.camporganizer.profile.ProfileBean;

/**
 * 
 * @author jotty
 *
 */
@Named
@RequestScoped
public class SalesController extends Controller {
	private final static Logger LOGGER = LogManager.getLogger(SalesController.class);

	@Inject
	@Named("salesModel")
	private SalesModel model;
	
	@Inject
	private ProfileBean profileBean;

	private String toSales(Integer activeIndex) {
		FacesContext facesContext = FacesContext.getCurrentInstance();

		try {
			SalesGateway gw = new SalesGateway(facesContext);
			model.setBean(model.getBean() == null ? new SalesBean() : model.getBean());
			model.getBean().setCamps(new CampGateway(facesContext).getAllCampsFromView(false, profileBean.getPk(), EnumModule.business));
			model.getBean().setTraders(gw.getAllTraders());
			model.getBean().setProviders(gw.getAllProviders());
			model.setList(gw.getAllSales(profileBean.getPk()));
			model.setBudget(gw.getBudget());
			model.setYearly(gw.getYearly());
		} catch (DataAccessException e) {
			model.getBean().setCamps(new ArrayList<>());
			model.getBean().setTraders(new ArrayList<>());
			model.getBean().setProviders(new ArrayList<>());
			facesContext.addMessage(null,
					new FacesMessage(FacesMessage.SEVERITY_ERROR, "error on loading camps", e.getMessage()));
			LOGGER.error(e.getMessage(), e);
		}
		model.setActiveIndex(activeIndex);
		return "/pages/sales.jsf";
	}

	public String toSales() {
		return toSales(0);
	}

	public String toEdit(SalesBean selection) {
		model.setBean(selection);
		FacesContext facesContext = FacesContext.getCurrentInstance();
		try {
			model.getBean().setRecipeshot(new SalesGateway(facesContext).getRecipeShot(model.getBean().getPk()));
		} catch (DataAccessException e) {
			facesContext.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_WARN, "error on loading recipe shot, saving may corrupt existing recipes", e.getMessage()));
		}
		return toSales();
	}
	
	public String doDelete(SalesBean selection) {
		FacesContext facesContext = FacesContext.getCurrentInstance();

		try {
			SalesGateway gw = new SalesGateway(facesContext);
			gw.delete(selection);
			model.setList(gw.getAllSales(profileBean.getPk()));
			return toSales(1);
		} catch (DataAccessException e) {
			facesContext.addMessage(null,
					new FacesMessage(FacesMessage.SEVERITY_ERROR, "error on deleting entry", e.getMessage()));
			return toSales(0);
		}
	}

	public String doUpsert() {
		FacesContext facesContext = FacesContext.getCurrentInstance();

		try {
			SalesGateway gw = new SalesGateway(facesContext);
			model.getBean().uploadFile();
			gw.upsert(model.getBean());
			model.setList(gw.getAllSales(profileBean.getPk()));
			model.clearBean();
			return toSales(1);
		} catch (DataAccessException | IOException e) {
			facesContext.addMessage(null,
					new FacesMessage(FacesMessage.SEVERITY_ERROR, "error on adding entry", e.getMessage()));
			return toSales(0);
		}
	}

	public String doDownload(SalesBean selection) {
		FacesContext facesContext = FacesContext.getCurrentInstance();

		try {
			byte[] data = new SalesGateway(facesContext).getRecipeShot(selection.getPk());
			
			if (data != null) {
				ExternalContext ec = facesContext.getExternalContext();
				ec.responseReset();
				ec.setResponseContentType(selection.getRecipeContentType());
				ec.setResponseContentLength(data.length);
				ec.setResponseHeader("Content-Disposition", "attachment; filename=\"" + selection.getRecipefilename() + "\"");
				OutputStream out = ec.getResponseOutputStream();
				out.write(data);
				out.flush();
				facesContext.responseComplete();
			} else {
				LOGGER.warn("image contains not data (is null)");
				facesContext.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_WARN, "error on downloading file",
						"Kassenzettel enthält keinen Inhalt"));
			}
		} catch (IOException e) {
			LOGGER.error(e.getMessage(), e);
			facesContext.addMessage(null,
					new FacesMessage(FacesMessage.SEVERITY_ERROR, "error on downloading file", e.getMessage()));
		}
		return toSales(1);
	}

	public SalesBean getBean() {
		return model.getBean();
	}

	public void setModel(SalesModel model) {
		this.model = model;
	}

	public ProfileBean getProfileBean() {
		return profileBean;
	}

	public void setProfileBean(ProfileBean profileBean) {
		this.profileBean = profileBean;
	}
}

src/main/java/de/jottyfan/camporganizer/modules/registrator/RegistratorBean.java
package de.jottyfan.camporganizer.modules.registrator;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.Period;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;

import de.jottyfan.camporganizer.db.converter.EnumConverter;
import de.jottyfan.camporganizer.db.jooq.enums.EnumCamprole;
import de.jottyfan.camporganizer.db.jooq.enums.EnumSex;
import de.jottyfan.camporganizer.modules.subscriber.PersondocumentBean;

/**
 * 
 * @author jotty
 *
 */
public class RegistratorBean {
	private final Integer pk;
	private String forename;
	private String surname;
	private String street;
	private String zip;
	private String city;
	private String phone;
	private Date birthdate;
	private EnumSex sex;
	private String email;
	private BigDecimal paid;
	private Date created;
	private String campname;
	private Integer minAge;
	private Integer maxAge;
	private Date arrive;
	private Date depart;
	private EnumCamprole camprole;
	private Boolean accept;
	private String profileForename;
	private String profileSurname;
	private String profileUUID;
	private String registratorForename;
	private String registratorSurname;
	private List<PersondocumentBean> documents;
	private String comment;

	public RegistratorBean(Integer pk) {
		super();
		this.pk = pk;
		this.documents = new ArrayList<>();
	}

	public String getNote() {
		StringBuilder buf = new StringBuilder();
		if (accept == null) {
			if (profileForename == null && profileSurname == null) {
				buf.append("! bitte per Post bestätigen\n");
			} else {
				buf.append("* angemeldet von ");
				buf.append(profileForename).append(" ").append(profileSurname).append("\n");
			}
		} else if (accept) {
			if (profileForename == null && profileSurname == null) {
				buf.append(" per Post bestätigt\n");
			}
			buf.append("* bestätigt von ");
			buf.append(registratorForename == null ? "unbekannt" : registratorForename);
			buf.append(" ");
			buf.append(registratorSurname == null ? "" : registratorSurname);
			buf.append("\n");
		} else {
			if (profileForename == null && profileSurname == null) {
				buf.append(" per Post auf Warteliste\n");
			}
			buf.append("* abgelehnt von ");
			buf.append(registratorForename == null ? "unbekannt" : registratorForename);
			buf.append(" ");
			buf.append(registratorSurname == null ? "" : registratorSurname);
			buf.append("\n");
		}
		if (birthdate != null) {
			if (arrive != null && depart != null) {
				// check birthdate in camp
				Calendar aDate = new GregorianCalendar();
				Calendar dDate = new GregorianCalendar();
				Calendar bDate = new GregorianCalendar();
				aDate.setTime(arrive);
				dDate.setTime(depart);
				bDate.setTime(birthdate);
				bDate.set(Calendar.YEAR, aDate.get(Calendar.YEAR));
				if (aDate.before(bDate) && dDate.after(bDate)) {
					buf.append("! hat während der Freizeit Geburtstag\n");
				}
			}
			if (minAge != null && maxAge != null) {
				Calendar aCal = new GregorianCalendar();
				Calendar bCal = new GregorianCalendar();
				aCal.setTime(arrive);
				bCal.setTime(birthdate);
				LocalDate aDate = LocalDate.of(aCal.get(Calendar.YEAR), aCal.get(Calendar.MONTH) + 1, aCal.get(Calendar.DATE));
				LocalDate bDate = LocalDate.of(bCal.get(Calendar.YEAR), bCal.get(Calendar.MONTH) + 1, bCal.get(Calendar.DATE));
				Integer years = Period.between(bDate, aDate).getYears();
				if (years < minAge || years > maxAge) {
					// ignore helpers and kitchen
					if (EnumCamprole.student.equals(camprole)) {
						buf.append("! passt vom Alter her nicht in die Freizeit\n");
					}
				}
			}
		}
		if (comment != null && !comment.trim().isEmpty()) {
			buf.append(comment);
		}
		return buf.toString();
	}

	public String getForename() {
		return forename;
	}

	public void setForename(String forename) {
		this.forename = forename;
	}

	public String getSurname() {
		return surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getStreet() {
		return street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	public String getZip() {
		return zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public Date getBirthdate() {
		return birthdate;
	}

	public void setBirthdate(Date birthdate) {
		this.birthdate = birthdate;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getCampname() {
		return campname;
	}

	public void setCampname(String campname) {
		this.campname = campname;
	}

	public Integer getMinAge() {
		return minAge;
	}

	public void setMinAge(Integer minAge) {
		this.minAge = minAge;
	}

	public Integer getMaxAge() {
		return maxAge;
	}

	public void setMaxAge(Integer maxAge) {
		this.maxAge = maxAge;
	}

	public Date getArrive() {
		return arrive;
	}

	public void setArrive(Date arrive) {
		this.arrive = arrive;
	}

	public Date getDepart() {
		return depart;
	}

	public void setDepart(Date depart) {
		this.depart = depart;
	}

	public Integer getPk() {
		return pk;
	}

	public String getCamproleGerman() {
		return new EnumConverter().getCamproleGerman(camprole);
	}

	public String getSexGerman() {
		return new EnumConverter().getSexGerman(sex);
	}

	public EnumCamprole getCamprole() {
		return camprole;
	}

	public void setCamprole(EnumCamprole camprole) {
		this.camprole = camprole;
	}

	public Boolean getAccept() {
		return accept;
	}

	public void setAccept(Boolean accept) {
		this.accept = accept;
	}

	public String getProfileForename() {
		return profileForename;
	}

	public void setProfileForename(String profileForename) {
		this.profileForename = profileForename;
	}

	public String getProfileSurname() {
		return profileSurname;
	}

	public void setProfileSurname(String profileSurname) {
		this.profileSurname = profileSurname;
	}

	public String getProfileUUID() {
		return profileUUID;
	}

	public void setProfileUUID(String profileUUID) {
		this.profileUUID = profileUUID;
	}

	public List<PersondocumentBean> getDocuments() {
		return documents;
	}

	public Date getCreated() {
		return created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public EnumSex getSex() {
		return sex;
	}

	public void setSex(EnumSex sex) {
		this.sex = sex;
	}

	public String getRegistratorForename() {
		return registratorForename;
	}

	public void setRegistratorForename(String registratorForename) {
		this.registratorForename = registratorForename;
	}

	public String getRegistratorSurname() {
		return registratorSurname;
	}

	public void setRegistratorSurname(String registratorSurname) {
		this.registratorSurname = registratorSurname;
	}

	public String getComment() {
		return comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	/**
	 * @return the paid
	 */
	public BigDecimal getPaid() {
		return paid;
	}

	/**
	 * @param paid the paid to set
	 */
	public void setPaid(BigDecimal paid) {
		this.paid = paid;
	}
}

src/main/webapp/pages/registrator/edit.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html" xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core" xmlns:b="http://bootsfaces.net/ui">
<h:body>
	<ui:composition template="/pages/template.xhtml">
		<ui:define name="content">
			<b:panel rendered="#{profileBean.hasRole('registrator')}" title="Korrektur der Anmeldung" collapsible="false">
				<b:form>
					<b:panelGrid colSpans="3,9" size="xs">
						<h:outputText value="Vorname" />
						<b:inputText value="#{registratorModel.bean.forename}" />
						<h:outputText value="Nachname" />
						<b:inputText value="#{registratorModel.bean.surname}" />
						<h:outputText value="Strasse" />
						<b:inputText value="#{registratorModel.bean.street}" />
						<h:outputText value="PLZ" />
						<b:inputText value="#{registratorModel.bean.zip}" />
						<h:outputText value="Ort" />
						<b:inputText value="#{registratorModel.bean.city}" />
						<h:outputText value="Geburtstag" />
						<b:datepicker value="#{registratorModel.bean.birthdate}" />
						<h:outputText value="Geschlecht" />
						<b:selectOneMenu value="#{registratorModel.bean.sex}">
							<f:selectItem itemLabel="weiblich" itemValue="female" />
							<f:selectItem itemLabel="männlich" itemValue="male" />
						</b:selectOneMenu>
						<h:outputText value="Telefon" />
						<b:inputText value="#{registratorModel.bean.phone}" />
						<h:outputText value="E-Mail" />
						<b:inputText value="#{registratorModel.bean.email}" />
						<h:outputText value="Rolle" />
						<h:outputText value="#{registratorModel.bean.camproleGerman}" />
						<h:outputText value="Freizeit" />
						<h:outputText value="#{registratorModel.bean.campname}" />
						<h:outputText value="Bemerkungen" />
						<b:inputTextarea value="#{registratorModel.bean.comment}" />
						<h:outputText value="Anmerkungen" />
						<h:outputText value="#{registratorModel.bean.note}" />
						<h:outputText value="überwiesener Betrag in €" />
						<b:inputText value="#{registratorModel.bean.paid}" mask="9{1,4}[.99]" />
						<b:commandButton action="#{registratorController.toMain}" value="abbrechen" imediate="true" />
						<b:commandButton action="#{registratorController.doUpdate}" value="korrigieren" look="warning" />
					</b:panelGrid>
				</b:form>
			</b:panel>
		</ui:define>
	</ui:composition>
</h:body>
</html>

src/main/webapp/pages/registrator/main.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html" xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core" xmlns:b="http://bootsfaces.net/ui">
<h:body>
	<ui:composition template="/pages/template.xhtml">
		<ui:define name="content">
			<b:panel rendered="#{profileBean.hasRole('registrator')}" title="Bestätigung" collapsible="false">
				<b:alert severity="info" closable="true">
					<h:outputText value="Der RSS-Feed des Registrators lautet: " />
					<b:navLink href="https://www.onkelwernerfreizeiten.de/camporganizer/rss.jsf?recipientCode=registrator" target="#"
						value="https://www.onkelwernerfreizeiten.de/camporganizer/rss.jsf?recipientCode=registrator" iconAwesome="rss" />
				</b:alert>
				<b:form>
					<b:dataTable value="#{registratorModel.list}" var="l" lang="de">
						<b:dataTableColumn label="Bestätigung">
							<div>
								<b:label text="bestätigt" severity="success" rendered="#{l.accept}" />
								<b:label text="abgelehnt" severity="warning" rendered="#{l.accept == false}" />
							</div>
							<b:buttonGroup>
								<b:commandButton action="#{registratorController.doAccept(l)}" value="" title="bestätigen" look="success"
									iconAwesome="check" rendered="#{l.accept != true}" />
								<!-- null or false -->
								<b:commandButton action="#{registratorController.doReject(l)}" value="" title="ablehnen" look="warning"
									iconAwesome="frown-o" rendered="#{l.accept == null}" />
								<b:dropButton value=" x " title="löschen" rendered="#{l.accept != null}">
									<b:commandButton action="#{registratorController.doDelete(l.pk)}" value="ja, unwiederbringlich löschen" look="danger" />
									<b:commandButton action="#{registratorController.doReset(l)}" value="Bestätigung zurücknehmen (Teilnehmer wird informiert)" look="warning"  rendered="#{l.accept}" />
								</b:dropButton>
							</b:buttonGroup>
						</b:dataTableColumn>
						<b:dataTableColumn label="Vorname">
							<h:outputText value="#{l.forename}" />
						</b:dataTableColumn>
						<b:dataTableColumn label="Nachname">
							<h:outputText value="#{l.surname}" />
						</b:dataTableColumn>
						<b:dataTableColumn label="Adresse/Kontakt">
							<h:outputText value="#{l.street}, #{l.zip} #{l.city}" /><br />
							<h:outputText value="#{l.phone}" /><br />
							<a href="mailto:#{l.email}"><h:outputText value="#{l.email}" /></a>
						</b:dataTableColumn>
						<b:dataTableColumn label="Geburtstag" dataType="date" dataOrder="#{l.birthdate}">
							<h:outputText value="#{l.birthdate}">
								<f:convertDateTime pattern="dd.MM.yyyy" />
							</h:outputText>
						</b:dataTableColumn>
						<b:dataTableColumn label="Rolle">
						  <h:outputText value="#{l.sexGerman}" /><br />
							<h:outputText value="#{l.camproleGerman}" />
						</b:dataTableColumn>
						<b:dataTableColumn label="Freizeit">
							<h:outputText value="#{l.campname}" />
						</b:dataTableColumn>
						<b:dataTableColumn label="Bemerkungen">
							<h:outputText value="#{l.note}" />
							<h:dataTable value="#{l.documents}" var="d">
								<h:column>
									<b:commandButton action="#{registratorController.doDownloadDocument(d)}" value="#{d.name}" iconAwesome="download" />
                  <b:dropButton value="" look="danger" iconAwesome="trash-o">
                    <b:commandButton action="#{registratorController.doDeleteDocument(d)}" value="Dokument endgültig löschen" iconAwesome="trash-o" look="link"/>
                  </b:dropButton>
								</h:column>
							</h:dataTable>
						</b:dataTableColumn>
						<b:dataTableColumn label="Erstellt" dataType="date" dataOrder="#{l.created}">
						  <h:outputText value="#{l.created}">
						    <f:convertDateTime pattern="dd.MM.yyyy HH:mm" />
						  </h:outputText>
						</b:dataTableColumn>
						<b:dataTableColumn label="">
							<b:commandButton action="#{registratorController.toEdit(l)}" value="" title="korrigieren" look="warning"
								iconAwesome="pencil" />
						</b:dataTableColumn>
					</b:dataTable>
				</b:form>
				<b:form>
					<b:panelGrid colSpans="9,3" size="sm">
						<b:selectOneMenu value="#{registratorModel.campPk}" styleClass="filterdropdown" required="true"
							requiredMessage="bitte eine Freizeit zum Herunterladen auswählen">
							<f:selectItem itemValue="" itemLabel="--- bitte wählen ---" />
							<f:selectItems value="#{registratorModel.camps}" var="c" itemValue="#{c.pk}" itemLabel="#{c.fullCampname}" />
						</b:selectOneMenu>
						<b:commandButton action="#{registratorController.doDownloadCampAsCsv}" value="herunterladen" iconAwesome="download" />
					</b:panelGrid>
				</b:form>
			</b:panel>
		</ui:define>
	</ui:composition>
</h:body>
</html>