src/main/java/de/jottyfan/camporganizer/CampBean.java
package de.jottyfan.camporganizer;

import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author jotty
 *
 */
public class CampBean {
	private Integer pk;
	private String name;
	private Integer fkLocation;
	private String locationName;
	private Integer year;
	private Integer minAge;
	private Integer maxAge;
	private String url;
	private Date arrive;
	private Date depart;
	private String price;
	private String countries;
	private Integer fkDocument;
	private Integer bookings;
	private Boolean lockSales;
	private Integer fkProfile;

	public String getFullCampname() {
		StringBuilder buf = new StringBuilder();
		buf.append(name).append(" ");
		buf.append(year).append(" in ");
		buf.append(locationName);
		return buf.toString();
	}

	public String getCampTime() {
		StringBuilder buf = new StringBuilder();
		buf.append(new SimpleDateFormat("E dd.MM.").format(arrive));
		buf.append(" - ");
		buf.append(new SimpleDateFormat("E dd.MM.yyyy").format(depart));
		return buf.toString();
	}

	public Integer getPk() {
		return pk;
	}

	public void setPk(Integer pk) {
		this.pk = pk;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getYear() {
		return year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}

	public String getLocationName() {
		return locationName;
	}

	public void setLocationName(String locationName) {
		this.locationName = locationName;
	}

	public Integer getMinAge() {
		return minAge;
	}

	public void setMinAge(Integer minAge) {
		this.minAge = minAge;
	}

	public Integer getMaxAge() {
		return maxAge;
	}

	public void setMaxAge(Integer maxAge) {
		this.maxAge = maxAge;
	}

	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public Date getArrive() {
		return arrive;
	}

	public void setArrive(Date arrive) {
		this.arrive = arrive;
	}

	public Date getDepart() {
		return depart;
	}

	public void setDepart(Date depart) {
		this.depart = depart;
	}

	public String getPrice() {
		return price;
	}

	public void setPrice(String price) {
		this.price = price;
	}

	public String getCountries() {
		return countries;
	}

	public void setCountries(String countries) {
		this.countries = countries;
	}

	public Integer getFkDocument() {
		return fkDocument;
	}

	public void setFkDocument(Integer fkDocument) {
		this.fkDocument = fkDocument;
	}

	public Integer getFkLocation() {
		return fkLocation;
	}

	public void setFkLocation(Integer fkLocation) {
		this.fkLocation = fkLocation;
	}

	public Integer getBookings() {
		return bookings;
	}

	public void setBookings(Integer bookings) {
		this.bookings = bookings;
	}

	public Boolean getLockSales() {
		return lockSales;
	}

	public void setLockSales(Boolean lockSales) {
		this.lockSales = lockSales;
	}

	public Integer getFkProfile() {
		return fkProfile;
	}

	public void setFkProfile(Integer fkProfile) {
		this.fkProfile = fkProfile;
	}
}

src/main/java/de/jottyfan/camporganizer/Controller.java
package de.jottyfan.camporganizer;

import java.io.IOException;
import java.io.OutputStream;
import java.util.Base64;

import javax.faces.application.FacesMessage;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;

import de.jottyfan.camporganizer.db.PersondocumentGateway;
import de.jottyfan.camporganizer.modules.subscriber.PersondocumentBean;

/**
 *
 * @author jotty
 *
 */
public abstract class Controller {
	public String toLogin() {
		return "/pages/login.jsf";
	}

	public String toProfile() {
		return "/pages/profile.jsf";
	}

	public String toRegister() {
		return "/pages/register.jsf";
	}

	/**
	 * download file encoded in base64
	 *
	 * @param contentBase64
	 * @param filetype
	 * @return empty string for an error
	 */
	public String doDownloadBase64(FacesContext facesContext, String contentBase64, String name, String filetype) {
		if (contentBase64 == null || contentBase64.isBlank()) {
			facesContext.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "error on downloading",
					"Das Dokument ist leer und enthält kein Daten."));
		} else {
			byte[] decodedContent = Base64.getDecoder().decode(contentBase64);
			ExternalContext ec = facesContext.getExternalContext();
			ec.responseReset();
			ec.setResponseContentType(filetype);
			ec.setResponseContentLength(decodedContent.length);
			ec.setResponseHeader("Content-Disposition", "attachment; filename=\"" + name + "." + filetype + "\"");
			try {
				OutputStream out = ec.getResponseOutputStream();
				out.write(decodedContent);
				out.flush();
				facesContext.responseComplete();
			} catch (IOException e) {
				facesContext.addMessage(null,
						new FacesMessage(FacesMessage.SEVERITY_ERROR, "error on downloading", e.getMessage()));
			}
		}
		return "";
	}
}

src/main/java/de/jottyfan/camporganizer/ical/IcalController.java
package de.jottyfan.camporganizer.ical;

import java.io.IOException;
import java.io.Writer;

import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.inject.Named;

import org.jooq.exception.DataAccessException;

import biweekly.Biweekly;
import biweekly.ICalendar;
import de.jottyfan.camporganizer.db.IcalGateway;

/**
 * 
 * @author jotty
 *
 */
@Named
@RequestScoped
public class IcalController {

	public String toIcal() {
		FacesContext facesContext = FacesContext.getCurrentInstance();
		ICalendar ical = null;
		try {
			ical = new IcalGateway(facesContext).getIcal();
		} catch (DataAccessException e) {
			facesContext.addMessage(null,
					new FacesMessage(FacesMessage.SEVERITY_ERROR, "error on reading ical from db", e.getMessage()));
		}
		ExternalContext ec = facesContext.getExternalContext();
		ec.responseReset();
		ec.setResponseCharacterEncoding("UTF-8");
		ec.setResponseContentType("text/calendar");
		ec.setResponseHeader("Content-Disposition", "attachment; filename=\"onkelwernerfreizeiten.de.ical\"");
		Writer writer;
		try {
			writer = ec.getResponseOutputWriter();
			writer.write(Biweekly.write(ical).go());
			writer.flush();
			facesContext.responseComplete();
		} catch (IOException e) {
			facesContext.addMessage(null,
					new FacesMessage(FacesMessage.SEVERITY_ERROR, "writing ical failed", e.getMessage()));
		}
		return "";
	}
}

src/main/java/de/jottyfan/camporganizer/jsf/ApplicationBean.java
package de.jottyfan.camporganizer.jsf;

import java.io.IOException;
import java.util.Properties;

import javax.enterprise.context.RequestScoped;
import javax.faces.context.FacesContext;
import javax.inject.Named;

/**
 * 
 * @author jotty
 *
 */
@Named
@RequestScoped
public class ApplicationBean {

	/**
	 * get version from maven build
	 * 
	 * @param facesContext
	 * @return
	 */
	public String getVersion(FacesContext facesContext) {
		final Properties prop = new Properties();
		try {
			prop.load(facesContext.getExternalContext().getResourceAsStream("/META-INF/MANIFEST.MF"));
			String version = prop.getProperty("Implementation-Version");
			return new StringBuilder("Version ").append(version == null ? prop.toString() : version).toString();
		} catch (final IOException e) {
			return e.getMessage();
		}
	}
}

src/main/java/de/jottyfan/camporganizer/modules/admin/ProfileRoleBean.java
package de.jottyfan.camporganizer.modules.admin;

import java.util.ArrayList;
import java.util.List;

import de.jottyfan.camporganizer.db.jooq.enums.EnumRole;
import de.jottyfan.camporganizer.profile.ProfileBean;

/**
 * 
 * @author jotty
 *
 */
public class ProfileRoleBean {
	private ProfileBean user;
	private final List<String> roles;
	private final EnumRole[] availableRoles;

	public ProfileRoleBean(EnumRole[] availableRoles) {
		this.availableRoles = availableRoles;
		this.roles = new ArrayList<>();
	}

	public List<String> getNotRoles() {
		List<String> notRoles = new ArrayList<>();
		for (EnumRole role : availableRoles) {
			if (!roles.contains(role.getLiteral())) {
				notRoles.add(role.getLiteral());
			}
		}
		notRoles.sort((o1, o2) -> o1 == null ? 0 : o1.compareTo(o2));
		return notRoles;
	}

	public ProfileBean getUser() {
		return user;
	}

	public void setUser(ProfileBean user) {
		this.user = user;
	}

	public List<String> getRoles() {
		roles.sort((o1, o2) -> o1 == null ? 0 : o1.compareTo(o2));
		return roles;
	}

	public void addRole(String role) {
		this.roles.add(role);
	}
}

src/main/java/de/jottyfan/camporganizer/modules/book/PersonBean.java
package de.jottyfan.camporganizer.modules.book;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import javax.enterprise.context.SessionScoped;
import javax.inject.Named;

import com.opencsv.bean.CsvBindByName;
import com.opencsv.bean.CsvBindByPosition;
import com.opencsv.bean.CsvDate;

import de.jottyfan.camporganizer.CampBean;
import de.jottyfan.camporganizer.db.converter.EnumConverter;
import de.jottyfan.camporganizer.db.jooq.enums.EnumCamprole;
import de.jottyfan.camporganizer.db.jooq.enums.EnumSex;

/**
 * 
 * @author jotty
 *
 */
@Named
@SessionScoped
public class PersonBean implements Serializable {
	private static final long serialVersionUID = 1L;

	private Integer pk;
	
	@CsvBindByPosition(position = 0)
	@CsvBindByName(column = "Gezahlt")
	private String paid;

	@CsvBindByPosition(position = 1)
	@CsvBindByName(column = "Vorname")
	private String forename;

	@CsvBindByPosition(position = 2)
	@CsvBindByName(column = "Nachname")
	private String surname;

	@CsvBindByPosition(position = 3)
	@CsvBindByName(column = "Straße")
	private String street;

	@CsvBindByPosition(position = 4)
	@CsvBindByName(column = "PLZ")
	private String zip;

	@CsvBindByPosition(position = 5)
	@CsvBindByName(column = "Ort")
	private String city;

	@CsvBindByPosition(position = 6)
	@CsvBindByName(column = "Telefon")
	private String phone;

	@CsvBindByPosition(position = 7)
	@CsvBindByName(column = "E-Mail")
	private String email;

	@CsvBindByPosition(position = 8)
	@CsvBindByName(column = "Geburtstag")
	@CsvDate("dd.MM.yyyy")
	private Date birthdate;

	@CsvBindByPosition(position = 9)
	@CsvBindByName(column = "Geschlecht")
	private String sex;

	@CsvBindByPosition(position = 10)
	@CsvBindByName(column = "Rolle")
	private String camprole;

	@CsvBindByPosition(position = 11)
	@CsvBindByName(column = "Angenommen")
	private String accept;

	@CsvBindByPosition(position = 12)
	@CsvBindByName(column = "Kommentar")
	private String comment;

	@CsvBindByPosition(position = 13)
	@CsvBindByName(column = "Fotoeinverständnis")
	private Boolean consentCatalogPhoto;
	
	private Integer fkCamp;
	private Integer fkProfile;

	private List<CampBean> camps;

	/**
	 * generate csv headline
	 * 
	 * @return headline
	 */
	public static final String getHeadline() {
		return "Gezahlt,Vorname,Nachname,Straße,PLZ,Ort,Telefon,E-Mail,Geburtstag,Geschlecht,Rolle,Angenommen,Kommentar,Fotoeinverständnis\n";
	}

	public String getAddress() {
		return new StringBuilder("").append(street).append(", ").append(zip).append(" ").append(city).toString();
	}

	public String getFullname() {
		return new StringBuilder("").append(forename).append(" ").append(surname).toString();
	}

	public String getForename() {
		return forename;
	}

	public void setForename(String forename) {
		this.forename = forename;
	}

	public String getSurname() {
		return surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getStreet() {
		return street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	public String getZip() {
		return zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public Date getBirthdate() {
		return birthdate;
	}

	public void setBirthdate(Date birthdate) {
		this.birthdate = birthdate;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getCamprole() {
		return camprole;
	}

	public void setCamprole(String camprole) {
		this.camprole = camprole;
	}

	public Integer getFkCamp() {
		return fkCamp;
	}

	public void setFkCamp(Integer fkCamp) {
		this.fkCamp = fkCamp;
	}

	public List<CampBean> getCamps() {
		return camps;
	}

	public void setCamps(List<CampBean> camps) {
		this.camps = camps;
	}

	public Integer getFkProfile() {
		return fkProfile;
	}

	public void setFkProfile(Integer fkProfile) {
		this.fkProfile = fkProfile;
	}

	public Integer getPk() {
		return pk;
	}

	public void setPk(Integer pk) {
		this.pk = pk;
	}

	public String getSex() {
		return sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public EnumSex getSexEnum() {
		return new EnumConverter().getEnumSex(sex);
	}

	public EnumCamprole getCamproleEnum() {
		return new EnumConverter().getEnumCamprole(camprole);
	}

	public String getAccept() {
		return accept;
	}

	public void setAccept(Boolean accept) {
		this.accept = accept == null ? "unbearbeitet" : (accept ? "Ja" : "Nein");
	}

	public String getComment() {
		return comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	/**
	 * @return the consentCatalogPhoto
	 */
	public Boolean getConsentCatalogPhoto() {
		return consentCatalogPhoto;
	}

	/**
	 * @param consentCatalogPhoto the consentCatalogPhoto to set
	 */
	public void setConsentCatalogPhoto(Boolean consentCatalogPhoto) {
		this.consentCatalogPhoto = consentCatalogPhoto;
	}
	
	public void setPaid(String paid) {
		this.paid = paid;
	}
	
	public String getPaid() {
		return paid;
	}
}

src/main/java/de/jottyfan/camporganizer/modules/businessman/BudgetBean.java
package de.jottyfan.camporganizer.modules.businessman;

import java.math.BigDecimal;

/**
 * F
 * 
 * @author jotty
 *
 */
public class BudgetBean {
	private final String camp;
	private final Integer year;
	private final Float budget;

	public BudgetBean(String camp, Double year, BigDecimal budget) {
		super();
		this.camp = camp;
		this.year = year == null ? 0 : year.intValue();
		this.budget = budget == null ? 0.0f : budget.floatValue();
	}

	public String getCamp() {
		return camp;
	}

	public Float getBudget() {
		return budget;
	}
	
	public Integer getYear() {
		return year;
	}
}

src/main/java/de/jottyfan/camporganizer/modules/subscriber/SubscriberBean.java
package de.jottyfan.camporganizer.modules.subscriber;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;

import de.jottyfan.camporganizer.modules.campadmin.DocumentBean;

/**
 * 
 * @author jotty
 *
 */
public class SubscriberBean {
	private final Integer pkPerson;
	private final String fullname;
	private String locationname;
	private String campname;
	private Date arrive;
	private Date depart;
	private Boolean accept;
	private String url;
	private Boolean consentCatalogPhoto;
	private List<DocumentBean> documents;
	private List<PersondocumentBean> persondocuments;

	public SubscriberBean(Integer pkPerson, String fullname, Boolean consentCalalogPhoto) {
		this.pkPerson = pkPerson;
		this.fullname = fullname;
		this.consentCatalogPhoto = consentCalalogPhoto;
	}
	
	public String getCamptime() {
		StringBuilder buf = new StringBuilder();
		buf.append(new SimpleDateFormat("dd.MM").format(arrive).toString());
		buf.append(" - ");
		buf.append(new SimpleDateFormat("dd.MM.yyyy").format(depart).toString());
		return buf.toString();
	}
	
	public String getCampname() {
		return campname;
	}

	public void setCampname(String campname) {
		this.campname = campname;
	}

	public Boolean getAccept() {
		return accept;
	}

	public void setAccept(Boolean accept) {
		this.accept = accept;
	}

	public Date getArrive() {
		return arrive;
	}

	public void setArrive(Date arrive) {
		this.arrive = arrive;
	}

	public Date getDepart() {
		return depart;
	}

	public void setDepart(Date depart) {
		this.depart = depart;
	}

	public String getLocationname() {
		return locationname;
	}

	public void setLocationname(String locationname) {
		this.locationname = locationname;
	}

	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public List<DocumentBean> getDocuments() {
		return documents;
	}

	public void setDocuments(List<DocumentBean> documents) {
		this.documents = documents;
	}

	public Integer getPkPerson() {
		return pkPerson;
	}

	public String getFullname() {
		return fullname;
	}

	public List<PersondocumentBean> getPersondocuments() {
		return persondocuments;
	}

	public void setPersondocuments(List<PersondocumentBean> persondocuments) {
		this.persondocuments = persondocuments;
	}

	public Boolean getConsentCatalogPhoto() {
		return consentCatalogPhoto;
	}

	public void setConsentCatalogPhoto(Boolean consentCatalogPhoto) {
		this.consentCatalogPhoto = consentCatalogPhoto;
	}
}

src/main/webapp/pages/subscriber/edit.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html" xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core" xmlns:b="http://bootsfaces.net/ui">
<h:body>
	<ui:composition template="/pages/template.xhtml">
		<ui:define name="content">
			<b:panel title="Korrektur der Anmeldung" collapsible="false">
				<b:form>
					<b:panelGrid colSpans="3,9" size="xs">
						<h:outputText value="Vorname" />
						<b:inputText value="#{subscriberModel.bean.forename}" />
						<h:outputText value="Nachname" />
						<b:inputText value="#{subscriberModel.bean.surname}" />
						<h:outputText value="Strasse" />
						<b:inputText value="#{subscriberModel.bean.street}" />
						<h:outputText value="PLZ" />
						<b:inputText value="#{subscriberModel.bean.zip}" />
						<h:outputText value="Ort" />
						<b:inputText value="#{subscriberModel.bean.city}" />
						<h:outputText value="Geburtstag" />
						<b:datepicker value="#{subscriberModel.bean.birthdate}" />
						<h:outputText value="Geschlecht" />
						<b:selectOneMenu value="#{subscriberModel.bean.sex}">
							<f:selectItem itemLabel="weiblich" itemValue="female" />
							<f:selectItem itemLabel="männlich" itemValue="male" />
						</b:selectOneMenu>
						<h:outputText value="Telefon" />
						<b:inputText value="#{subscriberModel.bean.phone}" />
						<h:outputText value="E-Mail" />
						<b:inputText value="#{subscriberModel.bean.email}" />
						<h:outputText value="Rolle" />
						<b:selectOneMenu value="#{subscriberModel.bean.camprole}">
							<f:selectItem itemValue="" itemLabel="--- bitte wählen ---" />
							<f:selectItem itemValue="student" itemLabel="Teilnehmer" />
							<f:selectItem itemValue="teacher" itemLabel="Mitarbeiter" />
							<f:selectItem itemValue="director" itemLabel="Leiter" />
							<f:selectItem itemValue="feeder" itemLabel="Küche" />
						</b:selectOneMenu>
						<b:commandButton action="#{subscriberController.toMain}" value="abbrechen" imediate="true" />
						<b:commandButton action="#{subscriberController.doUpdate}" value="korrigieren" look="warning" />
					</b:panelGrid>
				</b:form>
			</b:panel>
		</ui:define>
	</ui:composition>
</h:body>
</html>

src/main/webapp/pages/subscriber/main.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html" xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:f="http://java.sun.com/jsf/core"
	xmlns:b="http://bootsfaces.net/ui">
<h:body>
	<ui:composition template="/pages/template.xhtml">
		<ui:define name="content">
			<b:panel title="Hier kannst Du Deine eingescannten oder abfotografierten Bestätigungen hochladen." rendered="#{profileBean.hasRole('subscriber')}" collapsed="true">
				<b:form enctype="multipart/form-data">
					<b:panelGrid colSpans="2,10" size="sm">
						<h:outputText value="Anmeldung" />
						<b:selectOneMenu value="#{subscriberModel.persondocument.fkPerson}" required="true" requiredMessage="Bitte die Anmeldung angeben.">
							<f:selectItem itemValue="" itemLabel="--- bitte wählen ---" />
							<f:selectItems value="#{subscriberModel.camps}" var="c" itemValue="#{c.pkPerson}" itemLabel="#{c.fullname} in #{c.campname} #{c.camptime}" noSelectionValue="#{c.accept}" />
						</b:selectOneMenu>
						<h:outputText value="Name" />
						<b:inputText value="#{subscriberModel.persondocument.name}" placeholder="Bitte den Namen der Datei eingeben, z.B. unterschriebene Bestätigung o.ä." required="true"
							requiredMessage="Bitte einen Namen angeben." />
						<h:outputText value="Foto, PDF" />
						<h:inputFile value="#{subscriberModel.persondocument.uploadfile}" required="true" requiredMessage="Bitte ein Foto oder eine PDF angeben." style="padding-bottom: 16px" />
						<h:outputText value="Dateityp" />
						<b:selectOneMenu value="#{subscriberModel.persondocument.filetype}" required="true" requiredMessage="Bitte den Dateityp auswählen.">
							<f:selectItem itemValue="" itemLabel="--- bitte wählen ---" />
							<f:selectItems value="#{subscriberModel.enumFiletypes}" var="e" itemValue="#{e}" itemLabel="#{e.literal}" />
						</b:selectOneMenu>
						<h:outputText value="" />
						<b:commandButton action="#{subscriberController.doAddUserDoc}" value="hochladen" look="primary" />
					</b:panelGrid>
				</b:form>
			</b:panel>
			<b:panel rendered="#{profileBean.hasRole('subscriber')}" title="bisherige Buchungen" collapsible="false">
				<b:form>
					<b:alert severity="info" closable="true">
					Für alle Freizeiten gelten diese <a href="http://www.crg-reisen.de/agbs/" target="_blank">AGB</a>
					</b:alert>
					<h:outputText value="Folgende Anmeldungen hast Du durchgeführt:" />
					<h:dataTable value="#{subscriberModel.camps}" var="c" rowClasses="odd,even" styleClass="width100percent">
						<h:column>
							<b:panelGrid colSpans="2,10" size="sm">
								<h:outputText value="Teilnehmer" class="mylabel" />
								<h:outputText value="#{c.fullname}" />
								<h:outputText value="Freizeit" class="mylabel" />
								<h:outputText value="#{c.campname} #{c.camptime}" />
								<h:outputText value="Ort" class="mylabel" />
								<ui:fragment>
									<a href="#{c.url}" target="_blank"> <h:outputText value="#{c.locationname}" /></a>
								</ui:fragment>
								<h:outputText value="Einverständnis für Fotos" class="mylabel" />
								<b:switch value="#{c.consentCatalogPhoto}" label="Fotos von mir dürfen im Katalog Urlaub mit Gottes Wort verwendet werden" offText="Nein" offColor="danger" onText="Ja" onColor="success"
									onchange="ajax:subscriberController.doSetConsent(c)" update="@form" />
								<h:outputText value="Dokumente" class="mylabel" />
								<h:panelGrid columns="1">
									<b:alert severity="info" closable="false" rendered="#{!c.accept}">
									  Die Bestätigungsdokumente sind erst nach der offiziellen Bestätigung einsehbar.
									</b:alert>
									<b:alert severity="info" closable="true" rendered="#{c.accept}">
										<strong>Dir wurde ein Freizeitplatz reserviert.</strong>
										Bitte fülle die hier downloadbaren Formulare vollständig aus und schicke sie zügig an uns zurück oder lade sie als eingescanntes oder abfotografiertes Bild über das oben stehende Formular hoch.
                   	</b:alert>
									<h:dataTable value="#{c.documents}" var="d" rendered="#{c.accept}">
										<h:column>
											<b:commandButton action="#{subscriberController.doDownloadDocument(d)}" value="#{d.name}" iconAwesome="download" />
										</h:column>
									</h:dataTable>
									<h:dataTable value="#{c.persondocuments}" var="d">
										<h:column>
											<b:buttonGroup>
												<b:commandButton action="#{subscriberController.doDownloadDocument(d)}" value="#{d.name}" iconAwesome="download" />
												<b:dropButton value="x" iconAwesome="trash-o" look="danger">
													<b:commandButton action="#{subscriberController.doDeleteUserDoc(d)}" value="ja, jetzt unwiederbringlich löschen" look="danger" />
												</b:dropButton>
											</b:buttonGroup>
										</h:column>
									</h:dataTable>
								</h:panelGrid>
								<h:outputText value="Storno" class="mylabel" />
								<ui:fragment>
									<h:outputText value="nur schriftlich" rendered="#{c.accept}" />
									<b:buttonGroup rendered="#{!c.accept}">
										<b:commandButton action="#{subscriberController.toEdit(c)}" value="bearbeiten" look="warning" iconAwesome="pencil" />
										<b:dropButton value="stornieren" iconAwesome="trash-o" look="danger">
											<b:commandButton action="#{subscriberController.doDelete(c)}" value="ja, jetzt unwiederbringlich stornieren" look="danger" />
										</b:dropButton>
									</b:buttonGroup>
								</ui:fragment>
							</b:panelGrid>
						</h:column>
					</h:dataTable>
				</b:form>
			</b:panel>
		</ui:define>
	</ui:composition>
</h:body>
</html>