src/main/java/de/jottyfan/camporganizer/modules/book/PersonBean.java
package de.jottyfan.camporganizer.modules.book;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import javax.enterprise.context.SessionScoped;
import javax.inject.Named;

import com.opencsv.bean.CsvBindByName;
import com.opencsv.bean.CsvBindByPosition;
import com.opencsv.bean.CsvDate;

import de.jottyfan.camporganizer.CampBean;
import de.jottyfan.camporganizer.db.converter.EnumConverter;
import de.jottyfan.camporganizer.db.jooq.enums.EnumCamprole;
import de.jottyfan.camporganizer.db.jooq.enums.EnumSex;

/**
 * 
 * @author jotty
 *
 */
@Named
@SessionScoped
public class PersonBean implements Serializable {
	private static final long serialVersionUID = 1L;

	private Integer pk;
	
	@CsvBindByPosition(position = 0)
	@CsvBindByName(column = "Gezahlt")
	private String paid;

	@CsvBindByPosition(position = 1)
	@CsvBindByName(column = "Vorname")
	private String forename;

	@CsvBindByPosition(position = 2)
	@CsvBindByName(column = "Nachname")
	private String surname;

	@CsvBindByPosition(position = 3)
	@CsvBindByName(column = "Straße")
	private String street;

	@CsvBindByPosition(position = 4)
	@CsvBindByName(column = "PLZ")
	private String zip;

	@CsvBindByPosition(position = 5)
	@CsvBindByName(column = "Ort")
	private String city;

	@CsvBindByPosition(position = 6)
	@CsvBindByName(column = "Telefon")
	private String phone;

	@CsvBindByPosition(position = 7)
	@CsvBindByName(column = "E-Mail")
	private String email;

	@CsvBindByPosition(position = 8)
	@CsvBindByName(column = "Geburtstag")
	@CsvDate("dd.MM.yyyy")
	private Date birthdate;

	@CsvBindByPosition(position = 9)
	@CsvBindByName(column = "Geschlecht")
	private String sex;

	@CsvBindByPosition(position = 10)
	@CsvBindByName(column = "Rolle")
	private String camprole;

	@CsvBindByPosition(position = 11)
	@CsvBindByName(column = "Angenommen")
	private String accept;

	@CsvBindByPosition(position = 12)
	@CsvBindByName(column = "Kommentar")
	private String comment;

	@CsvBindByPosition(position = 13)
	@CsvBindByName(column = "Fotoeinverständnis")
	private Boolean consentCatalogPhoto;
	
	private Integer fkCamp;
	private Integer fkProfile;

	private List<CampBean> camps;

	/**
	 * generate csv headline
	 * 
	 * @return headline
	 */
	public static final String getHeadline() {
		return "Gezahlt,Vorname,Nachname,Straße,PLZ,Ort,Telefon,E-Mail,Geburtstag,Geschlecht,Rolle,Angenommen,Kommentar,Fotoeinverständnis\n";
	}

	public String getAddress() {
		return new StringBuilder("").append(street).append(", ").append(zip).append(" ").append(city).toString();
	}

	public String getFullname() {
		return new StringBuilder("").append(forename).append(" ").append(surname).toString();
	}

	public String getForename() {
		return forename;
	}

	public void setForename(String forename) {
		this.forename = forename;
	}

	public String getSurname() {
		return surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getStreet() {
		return street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	public String getZip() {
		return zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public Date getBirthdate() {
		return birthdate;
	}

	public void setBirthdate(Date birthdate) {
		this.birthdate = birthdate;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getCamprole() {
		return camprole;
	}

	public void setCamprole(String camprole) {
		this.camprole = camprole;
	}

	public Integer getFkCamp() {
		return fkCamp;
	}

	public void setFkCamp(Integer fkCamp) {
		this.fkCamp = fkCamp;
	}

	public List<CampBean> getCamps() {
		return camps;
	}

	public void setCamps(List<CampBean> camps) {
		this.camps = camps;
	}

	public Integer getFkProfile() {
		return fkProfile;
	}

	public void setFkProfile(Integer fkProfile) {
		this.fkProfile = fkProfile;
	}

	public Integer getPk() {
		return pk;
	}

	public void setPk(Integer pk) {
		this.pk = pk;
	}

	public String getSex() {
		return sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public EnumSex getSexEnum() {
		return new EnumConverter().getEnumSex(sex);
	}

	public EnumCamprole getCamproleEnum() {
		return new EnumConverter().getEnumCamprole(camprole);
	}

	public String getAccept() {
		return accept;
	}

	public void setAccept(Boolean accept) {
		this.accept = accept == null ? "unbearbeitet" : (accept ? "Ja" : "Nein");
	}

	public String getComment() {
		return comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	/**
	 * @return the consentCatalogPhoto
	 */
	public Boolean getConsentCatalogPhoto() {
		return consentCatalogPhoto;
	}

	/**
	 * @param consentCatalogPhoto the consentCatalogPhoto to set
	 */
	public void setConsentCatalogPhoto(Boolean consentCatalogPhoto) {
		this.consentCatalogPhoto = consentCatalogPhoto;
	}
	
	public void setPaid(String paid) {
		this.paid = paid;
	}
	
	public String getPaid() {
		return paid;
	}
}

src/main/java/de/jottyfan/camporganizer/modules/businessman/SalesBean.java
package de.jottyfan.camporganizer.modules.businessman;

import java.io.IOException;
import java.io.InputStream;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.enterprise.context.SessionScoped;
import javax.inject.Named;
import javax.servlet.http.Part;

import org.apache.commons.io.IOUtils;

import de.jottyfan.camporganizer.CampBean;

/**
 * 
 * @author jotty
 *
 */
@Named
@SessionScoped
public class SalesBean implements Serializable {
	private static final long serialVersionUID = 1L;

	private Integer pk;
	private String trader;
	private Integer fkCamp;
	private String provider;
	private Float cash;
	private String incredients;
	private Date buydate;
	private String recipeNumber;
	private byte[] recipeshot;
	private Integer recipeshotSize;
	private String recipefilename;
	private String recipeNote;
	private Boolean lockSales;

	private Part file;

	private List<CampBean> camps;
	private List<String> traders;
	private List<String> providers;

	/**
	 * get name and year of camp
	 * 
	 * @param campId
	 *          to be used as a reference
	 * @return name and year if found, empty string otherwise
	 */
	public String getCampNameAndYear(Integer campId) {
		for (CampBean bean : camps) {
			if (bean.getPk().equals(campId)) {
				StringBuilder buf = new StringBuilder();
				buf.append(bean.getName()).append(" ").append(bean.getYear());
				return buf.toString();
			}
		}
		return "";
	}

	/**
	 * convert upload file content to recipeshot
	 * 
	 * @throws IOException
	 */
	public void uploadFile() throws IOException {
		if (file != null) {
			InputStream inputStream = file.getInputStream();
			byte[] bytes = IOUtils.toByteArray(inputStream);
			if (bytes.length > 0) {
				recipeshot = bytes;
				recipefilename = getFileName(file);
			} else {
				recipeshot = null;
				recipefilename = null;
			}
		}
	}

	/**
	 * get filename from part (from
	 * https://stackoverflow.com/questions/30810014/javax-servlet-http-part-to-java-io-file)
	 * 
	 * @param part
	 *          the part
	 * @return the filename if found or null
	 */
	private String getFileName(final Part part) {
		final String partHeader = part.getHeader("content-disposition");
		for (String content : partHeader.split(";")) {
			if (content.trim().startsWith("filename")) {
				return content.substring(content.indexOf('=') + 1).trim().replace("\"", "");
			}
		}
		return null;
	}

	/**
	 * get all unlocked camp beans
	 * 
	 * @return list of unlocked camp beans
	 */
	public List<CampBean> getUnlockedCamps() {
		List<CampBean> list = new ArrayList<>();
		for (CampBean bean : camps) {
			if (!bean.getLockSales()) {
				list.add(bean);
			}
		}
		return list;
	}

	/**
	 * get mime type from file name ending
	 * 
	 * @return the found mime type, the default if not supported or null on empty
	 *         filename
	 */
	public String getRecipeContentType() {
		if (recipefilename == null) {
			return null;
		} else if (recipefilename.toLowerCase().trim().endsWith(".pdf")) {
			return "application/pdf";
		} else if (recipefilename.toLowerCase().trim().endsWith(".jpg")
				|| recipefilename.toLowerCase().trim().endsWith(".jpeg")) {
			return "image/jpeg";
		} else if (recipefilename.toLowerCase().trim().endsWith(".png")) {
			return "image/png";
		} else {
			return "application/octet-stream";
		}
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("SalesBean [trader=");
		builder.append(trader);
		builder.append(", fkCamp=");
		builder.append(fkCamp);
		builder.append(", provider=");
		builder.append(provider);
		builder.append(", cash=");
		builder.append(cash);
		builder.append(", incredients=");
		builder.append(incredients);
		builder.append(", buydate=");
		builder.append(buydate);
		builder.append(", recipeNumber=");
		builder.append(recipeNumber);
		builder.append(", recipefilename=");
		builder.append(recipefilename);
		builder.append(", recipeNote=");
		builder.append(recipeNote);
		builder.append(", lockSales=");
		builder.append(lockSales);
		builder.append("]");
		return builder.toString();
	}

	public String getTrader() {
		return trader;
	}

	public void setTrader(String trader) {
		this.trader = trader;
	}

	public Integer getFkCamp() {
		return fkCamp;
	}

	public void setFkCamp(Integer fkCamp) {
		this.fkCamp = fkCamp;
	}

	public String getProvider() {
		return provider;
	}

	public void setProvider(String provider) {
		this.provider = provider;
	}

	public Float getCash() {
		return cash;
	}

	public BigDecimal getCashBigDecimal() {
		return cash == null ? null : new BigDecimal(cash);
	}

	public void setCash(Float cash) {
		this.cash = cash;
	}

	public Date getBuydate() {
		return buydate;
	}

	public void setBuydate(Date buydate) {
		this.buydate = buydate;
	}

	public String getRecipeNumber() {
		return recipeNumber;
	}

	public void setRecipeNumber(String recipeNumber) {
		this.recipeNumber = recipeNumber;
	}

	public String getRecipeNote() {
		return recipeNote;
	}

	public void setRecipeNote(String recipeNote) {
		this.recipeNote = recipeNote;
	}

	public List<CampBean> getCamps() {
		return camps;
	}

	public void setCamps(List<CampBean> camps) {
		this.camps = camps;
	}

	public String getIncredients() {
		return incredients;
	}

	public void setIncredients(String incredients) {
		this.incredients = incredients;
	}

	public byte[] getRecipeshot() {
		return recipeshot;
	}

	public void setRecipeshot(byte[] recipeshot) {
		this.recipeshot = recipeshot;
	}

	public Part getFile() {
		return file;
	}

	public void setFile(Part file) {
		this.file = file;
	}

	public Integer getPk() {
		return pk;
	}

	public void setPk(Integer pk) {
		this.pk = pk;
	}

	public List<String> getTraders() {
		return traders;
	}

	public void setTraders(List<String> traders) {
		this.traders = traders;
	}

	public List<String> getProviders() {
		return providers;
	}

	public void setProviders(List<String> providers) {
		this.providers = providers;
	}

	public Boolean getLockSales() {
		return lockSales;
	}

	public void setLockSales(Boolean lockSales) {
		this.lockSales = lockSales;
	}

	public String getRecipefilename() {
		return recipefilename;
	}

	public void setRecipefilename(String recipefilename) {
		this.recipefilename = recipefilename;
	}

	/**
	 * @return the recipeshotSize
	 */
	public Integer getRecipeshotSize() {
		return recipeshotSize;
	}

	/**
	 * @param recipeshotSize the recipeshotSize to set
	 */
	public void setRecipeshotSize(Integer recipeshotSize) {
		this.recipeshotSize = recipeshotSize;
	}
}

src/main/java/de/jottyfan/camporganizer/profile/ProfileBean.java
package de.jottyfan.camporganizer.profile;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import javax.enterprise.context.SessionScoped;
import javax.inject.Named;

import org.jasypt.exceptions.EncryptionOperationNotPossibleException;
import org.jasypt.util.password.StrongPasswordEncryptor;
import org.jooq.exception.DataAccessException;

/**
 * 
 * @author henkej
 *
 */
@Named
@SessionScoped
public class ProfileBean implements Serializable {
	private static final long serialVersionUID = 1L;

	private Integer pk;
	private String forename;
	private String surname;
	private String username;
	private String password;
	private String passwordAgain;
	private String uuid;
	private String encryptedPassword;
	private String roles;
	private Date duedate;
	private List<String> allUsernames;

	public void clear() {
		this.pk = null;
		this.forename = null;
		this.surname = null;
		this.username = null;
		this.password = null;
		this.passwordAgain = null;
		this.uuid = null;
		this.encryptedPassword = null;
		this.roles = null;
	}

	public boolean checkPasswordAndForgetPlainOne() throws DataAccessException {
		boolean result = false;
		try {
			result = new StrongPasswordEncryptor().checkPassword(password, encryptedPassword);
		} catch (EncryptionOperationNotPossibleException e) {
			return false; // password is not decryptable
		}
		if (result) {
			password = null;
			return result;
		} else {
			return false;
		}
	}

	public Boolean getIsEmpty() {
		return pk == null;
	}
	
	public Boolean getOutdated() {
		return duedate == null ? false : duedate.before(new Date()); // new Date() is now
	}

	public boolean hasRole(String role) {
		return roles == null ? false : roles.contains(role);
	}

	public String getFullname() {
		return new StringBuilder(forename == null ? "" : forename).append(" ").append(surname == null ? "" : surname)
				.toString();
	}

	public String getComparename() {
		return new StringBuilder(surname == null ? "" : surname.toLowerCase())
				.append(forename == null ? "" : forename.toLowerCase()).toString();
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return password;
	}

	public void setPasswordButKeepEncrypted(String password) {
		this.password = password;
	}

	/**
	 * use this from the web pages
	 * 
	 * @param password
	 */
	public void setPassword(String password) {
		this.password = password;
		this.encryptedPassword = new StrongPasswordEncryptor().encryptPassword(password);
	}

	public String getForename() {
		return forename;
	}

	public void setForename(String forename) {
		this.forename = forename;
	}

	public String getSurname() {
		return surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getEncryptedPassword() {
		return encryptedPassword;
	}

	/**
	 * use this in the gateway for database content only
	 * 
	 * @param encryptedPassword
	 */
	public void setEncryptedPassword(String encryptedPassword) {
		this.encryptedPassword = encryptedPassword;
	}

	public String getPasswordAgain() {
		return passwordAgain;
	}

	public void setPasswordAgain(String passwordAgain) {
		this.passwordAgain = passwordAgain;
	}

	public String getRoles() {
		return roles;
	}

	public void setRoles(String roles) {
		this.roles = roles;
	}

	public Integer getPk() {
		return pk;
	}

	public void setPk(Integer pk) {
		this.pk = pk;
	}

	public List<String> getAllUsernames() {
		return allUsernames;
	}

	public void setAllUsernames(List<String> allUsernames) {
		this.allUsernames = allUsernames;
	}

	public String getUuid() {
		return uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	/**
	 * @return the duedate
	 */
	public Date getDuedate() {
		return duedate;
	}

	/**
	 * @param duedate the duedate to set
	 */
	public void setDuedate(Date duedate) {
		this.duedate = duedate;
	}
}

src/main/java/de/jottyfan/camporganizer/rss/RssBean.java
package de.jottyfan.camporganizer.rss;

import java.util.Date;

/**
 *
 * @author jotty
 *
 */
public class RssBean {
	public final Integer pk;
	public String recipient;
	public String message;
	public Date pubdate;

	public RssBean(Integer pk) {
		this.pk = pk;
	}

	public String getMessage80() {
		return message == null ? null : (message.length() > 80 ? message.substring(0, 80).concat("...") : message);
	}

	public Integer getPk() {
		return pk;
	}

	public String getMessage() {
		return message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public Date getPubdate() {
		return pubdate;
	}

	public void setPubdate(Date pubdate) {
		this.pubdate = pubdate;
	}

	public String getRecipient() {
		return recipient;
	}

	public void setRecipient(String recipient) {
		this.recipient = recipient;
	}
}

src/main/webapp/pages/administrate.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html" xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core" xmlns:b="http://bootsfaces.net/ui">
<h:body>
	<ui:composition template="/pages/template.xhtml">
		<ui:define name="content">
			<b:panel rendered="#{profileBean.hasRole('admin')}" title="Administration" collapsible="false">
			  <b:alert severity="info" closable="true">
          <h:outputText value="Der RSS-Feed des Administrators lautet: " />
          <b:navLink href="https://www.onkelwernerfreizeiten.de/camporganizer/rss.jsf?recipientCode=admin" target="#" value="https://www.onkelwernerfreizeiten.de/camporganizer/rss.jsf?recipientCode=admin" iconAwesome="rss" />
        </b:alert>
				<b:tabView activeIndex="#{adminModel.activeIndex}">
					<b:tab title="Rollen verwalten" styleClass="dist16">
						<b:form>
							<b:dataTable value="#{adminModel.profileRoles}" var="l" lang="de">
								<b:dataTableColumn label="Nutzer" dataOrder="#{l.user.surname}">
									<h:outputText value="#{l.user.fullname}" />
									<f:facet name="footer">
										<b:selectOneMenu value="#{adminModel.profileRole.user}" select2="true">
											<f:selectItems value="#{adminModel.users}" var="u" itemLabel="#{u.fullname}" itemValue="#{u}" />
										</b:selectOneMenu>
									</f:facet>
								</b:dataTableColumn>
								<b:dataTableColumn label="Rollen">
									<ui:repeat value="#{l.roles}" var="r">
										<b:badge value="#{r}" styleClass="rolebadge role-#{r}" />
									</ui:repeat>
								</b:dataTableColumn>
								<b:dataTableColumn label="Änderungen">
									<b:dropButton value="Rollen ändern" look="warning">
										<ui:repeat value="#{l.roles}" var="r">
											<b:commandButton action="#{adminController.doDelete(l, r)}" value="#{r} entziehen" iconAwesome="trash-o" look="link" styleClass="dangertext" />
										</ui:repeat>
										<ui:repeat value="#{l.notRoles}" var="r">
											<b:commandButton action="#{adminController.doInsert(l, r)}" value="#{r} erlauben" iconAwesome="plus" look="link" />
										</ui:repeat>
									</b:dropButton>
									<f:facet name="footer">
										<b:dropButton value="Rolle anlegen" look="success" drop="up">
											<ui:repeat value="#{adminController.possibleRoles}" var="r">
												<b:commandButton action="#{adminController.doInsert(r)}" value="#{r} erlauben" iconAwesome="plus" look="link" />
											</ui:repeat>
										</b:dropButton>
									</f:facet>
								</b:dataTableColumn>
							</b:dataTable>
						</b:form>
					</b:tab>
					<b:tab title="Logins verwalten" styleClass="dist16">
						<b:form>
							<b:dataTable value="#{adminModel.users}" var="u" lang="de">
								<b:dataTableColumn label="Name">
									<h:outputText value="#{u.fullname}" />
								</b:dataTableColumn>
								<b:dataTableColumn label="Login">
									<h:outputText value="#{u.username}" />
								</b:dataTableColumn>
                <b:dataTableColumn label="Ablaufdatum">
                  <b:dateTimePicker value="#{u.duedate}" format="DD.MM.YYYY" locale="de" style="#{u.outdated ? 'border: 2px solid orange; border-radius: 6px' : ''}" />
                  <b:commandButton action="#{adminController.doResetDuedate(u)}" value="" look="#{u.outdated ? 'warning' : ''}" iconAwesome="check" tooltip="neues Datum übernehmen" />
                </b:dataTableColumn>
								<b:dataTableColumn label="Operationen">
									<b:buttonGroup>
										<b:commandButton action="#{adminController.doResetUserPassword(u)}" iconAwesome="flash" value="Passwort zurücksetzen"
											look="warning" />
										<b:dropButton value="löschen" iconAwesome="trash-o" look="danger">
											<b:commandButton action="#{adminController.doDeleteUser(u)}" value="ja, unwiederbringlich löschen" look="danger" />
										</b:dropButton>
									</b:buttonGroup>
								</b:dataTableColumn>
							</b:dataTable>
						</b:form>
					</b:tab>
          <b:tab title="RSS" styleClass="dist16">
            <b:tabView activeIndex="#{adminModel.activeIndexRss}">
              <b:tab title="Tabelle">
                <b:form>
                  <b:dataTable value="#{adminModel.rssList}" var="d" lang="de">
                    <b:dataTableColumn label="ID">
                      <b:commandButton action="#{adminController.toEditRss(d.pk)}" value="#{d.pk}" look="link" />
                    </b:dataTableColumn>
                    <b:dataTableColumn label="Empfänger">
                      <b:commandButton action="#{adminController.toEditRss(d.pk)}" value="#{d.recipient}" look="link" />
                    </b:dataTableColumn>
                    <b:dataTableColumn label="Inhalt">
                      <b:commandButton action="#{adminController.toEditRss(d.pk)}" value="#{d.message80}" look="link" />
                    </b:dataTableColumn>
                    <b:dataTableColumn label="Datum" dataType="date">
                      <b:commandButton action="#{adminController.toEditRss(d.pk)}" value="#{d.pubdate}" look="link" />
                    </b:dataTableColumn>
                  </b:dataTable>
                </b:form>
              </b:tab>
              <b:tab title="Element">
                <b:form>
                  <b:panelGrid colSpans="3,9" size="xs">
                    <h:outputText value="ID = #{adminModel.rss.pk}" />
                    <b:commandButton action="#{adminController.doResetRss}" value="Felder leeren" />
                    <h:outputText value="Empfänger" />
                    <h:outputText value="#{adminModel.rss.recipient}" />
                    <h:outputText value="Inhalt" />
                    <b:inputTextarea value="#{adminModel.rss.message}" />
                    <h:outputText value="Datum" />
                    <h:outputText value="#{adminModel.rss.pubdate}" />
                    <b:dropButton value="löschen" iconAwesome="trash-o" look="danger">
                      <b:commandButton action="#{adminController.doDeleteRss}" value="ja, unwiederbringlich löschen" look="danger" />
                    </b:dropButton>
                    <b:commandButton action="#{adminController.doUpdateRss}" value="Übernehmen" look="primary" />
                  </b:panelGrid>
                </b:form>
              </b:tab>
            </b:tabView>
          </b:tab>
				</b:tabView>
			</b:panel>
		</ui:define>
	</ui:composition>
</h:body>
</html>

src/main/webapp/pages/template.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html" xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:b="http://bootsfaces.net/ui">
<h:head>
	<h:outputStylesheet name="style.css?version=#{profileController.version}" library="css" />
	<h:outputScript name="jq/jquery.js?version=#{profileController.version}" library="bsf" />
	<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
	<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
</h:head>
<h:body>
	<div class="header">
		<b:form>
			<b:navBar fluid="true">
				<b:navbarLinks rendered="#{profileBean != null and !profileBean.isEmpty}">
					<b:navCommandLink action="#{profileController.toProfile}" value="#{profileBean.fullname}" />
					<b:navCommandLink action="#{profileController.doLogout}" value="abmelden" />
				</b:navbarLinks>
				<b:navbarLinks rendered="#{profileBean != null and !profileBean.isEmpty}">
					<b:navCommandLink action="#{subscriberController.toMain}" value="Buchung" iconAwesome="smile-o"
						rendered="#{profileBean.hasRole('subscriber')}" />
					<b:navCommandLink action="#{bookController.toBookWithProfile}" value="Anmeldung" iconAwesome="handshake-o" />
					<b:navCommandLink action="#{salesController.toSales}" value="Abrechnung" iconAwesome="money"
						rendered="#{profileBean.hasRole('businessman')}" />
					<b:navCommandLink action="#{adminController.toAdministrate}" value="Administration" iconAwesome="user-secret"
						rendered="#{profileBean.hasRole('admin')}" />
					<b:navCommandLink action="#{campadminController.toCampadmin}" value="Freizeitadministration" iconAwesome="graduation-cap"
						rendered="#{profileBean.hasRole('campadmin')}" />
					<b:navCommandLink action="#{registratorController.toMain}" value="Bestätigung" iconAwesome="user-o"
						rendered="#{profileBean.hasRole('registrator')}" />
				</b:navbarLinks>
				<b:navbarLinks>
					<ui:insert name="navigation" />
				</b:navbarLinks>
			</b:navBar>
		</b:form>
	</div>
	<div class="content">
		<div class="lrpadding">
			<b:messages />
		</div>
		<div class="lrpadding">
			<ui:insert name="content" />
		</div>
	</div>
	<div class="footer">
		<span style="left: 4px"> <a href="../ical.jsf" style="margin-right: 4px; margin-left: 4px"> <b:iconAwesome
					name="calendar" />&nbsp;ical
		</a>&nbsp;&nbsp;&nbsp; <a href="../dsgvo.jsf">Datenschutzerklärung</a> <ui:insert name="footer" />
		</span>
		<div style="position: absolute; right: 4px; display: inline">
			<h:outputText value="#{applicationBean.getVersion(facesContext)}" />
		</div>
	</div>
	<script type="text/javascript">
		$(document).ready(function() {
			$('.filterdropdown').select2();
			$(".select2-container").css("width", "100%");
		});
	</script>
</h:body>
</html>