src/main/java/de/jottyfan/camporganizer/CampBean.java
package de.jottyfan.camporganizer;

import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author jotty
 *
 */
public class CampBean {
	private Integer pk;
	private String name;
	private Integer fkLocation;
	private String locationName;
	private Integer year;
	private Integer minAge;
	private Integer maxAge;
	private String url;
	private Date arrive;
	private Date depart;
	private String price;
	private String countries;
	private Integer fkDocument;
	private Integer bookings;
	private Boolean lockSales;
	private Integer fkProfile;

	public String getFullCampname() {
		StringBuilder buf = new StringBuilder();
		buf.append(name).append(" ");
		buf.append(year).append(" in ");
		buf.append(locationName);
		return buf.toString();
	}

	public String getCampTime() {
		StringBuilder buf = new StringBuilder();
		buf.append(new SimpleDateFormat("E dd.MM.").format(arrive));
		buf.append(" - ");
		buf.append(new SimpleDateFormat("E dd.MM.yyyy").format(depart));
		return buf.toString();
	}

	public Integer getPk() {
		return pk;
	}

	public void setPk(Integer pk) {
		this.pk = pk;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getYear() {
		return year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}

	public String getLocationName() {
		return locationName;
	}

	public void setLocationName(String locationName) {
		this.locationName = locationName;
	}

	public Integer getMinAge() {
		return minAge;
	}

	public void setMinAge(Integer minAge) {
		this.minAge = minAge;
	}

	public Integer getMaxAge() {
		return maxAge;
	}

	public void setMaxAge(Integer maxAge) {
		this.maxAge = maxAge;
	}

	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public Date getArrive() {
		return arrive;
	}

	public void setArrive(Date arrive) {
		this.arrive = arrive;
	}

	public Date getDepart() {
		return depart;
	}

	public void setDepart(Date depart) {
		this.depart = depart;
	}

	public String getPrice() {
		return price;
	}

	public void setPrice(String price) {
		this.price = price;
	}

	public String getCountries() {
		return countries;
	}

	public void setCountries(String countries) {
		this.countries = countries;
	}

	public Integer getFkDocument() {
		return fkDocument;
	}

	public void setFkDocument(Integer fkDocument) {
		this.fkDocument = fkDocument;
	}

	public Integer getFkLocation() {
		return fkLocation;
	}

	public void setFkLocation(Integer fkLocation) {
		this.fkLocation = fkLocation;
	}

	public Integer getBookings() {
		return bookings;
	}

	public void setBookings(Integer bookings) {
		this.bookings = bookings;
	}

	public Boolean getLockSales() {
		return lockSales;
	}

	public void setLockSales(Boolean lockSales) {
		this.lockSales = lockSales;
	}

	public Integer getFkProfile() {
		return fkProfile;
	}

	public void setFkProfile(Integer fkProfile) {
		this.fkProfile = fkProfile;
	}
}

src/main/java/de/jottyfan/camporganizer/modules/campadmin/CampadminController.java
package de.jottyfan.camporganizer.modules.campadmin;

import java.io.IOException;
import java.util.Arrays;

import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.jooq.exception.DataAccessException;

import de.jottyfan.camporganizer.CampBean;
import de.jottyfan.camporganizer.Controller;
import de.jottyfan.camporganizer.db.CampGateway;
import de.jottyfan.camporganizer.db.CampprofileGateway;
import de.jottyfan.camporganizer.db.DocumentGateway;
import de.jottyfan.camporganizer.db.LocationGateway;
import de.jottyfan.camporganizer.db.ProfileGateway;
import de.jottyfan.camporganizer.db.jooq.enums.EnumDocument;
import de.jottyfan.camporganizer.db.jooq.enums.EnumFiletype;
import de.jottyfan.camporganizer.db.jooq.enums.EnumRole;

/**
 * 
 * @author jotty
 *
 */
@Named
@RequestScoped
public class CampadminController extends Controller {

	private static final Logger LOGGER = LogManager.getLogger(CampadminController.class);

	@Inject
	@Named("campadminModel")
	private CampadminModel model;
	
	private Boolean isAdding;

	public String toCampadmin() {
		FacesContext facesContext = FacesContext.getCurrentInstance();

		try {
			ProfileGateway gw = new ProfileGateway(facesContext);
			model.setEnumlistDoctype(Arrays.asList(EnumDocument.values()));
			model.setEnumlistFiletype(Arrays.asList(EnumFiletype.values()));
			if (model.getDocument() == null) {
				model.setDocument(new DocumentBean(null));
			}
			model.setDocuments(gw.getAllDocuments());

			if (model.getLocation() == null) {
				model.setLocation(new LocationBean(null));
			}
			model.setLocations(gw.getAllLocations());

			if (model.getCamp() == null) {
				model.setCamp(new CampBean());
			}
			model.setCamps(new CampGateway(facesContext).getAllCampsFromTable());
			model.setLocationNameToCamp();

			model.setProfiles(new ProfileGateway(facesContext).getAllUsersWithRole(EnumRole.registrator));
			model.orderProfiles();

			model.setCampprofiles(new CampprofileGateway(facesContext).getAll());
			model.setCampprofile(new CampprofileBean()); // editing makes no sense
		} catch (DataAccessException e) {
			facesContext.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "database error", e.getMessage()));
			LOGGER.error("AdminController.toAdministrate: ", e);
		}
		return "/pages/campadmin/edit.jsf";
	}

	public String toEditDocument(Integer pk) {
		model.setActiveIndex(2);
		for (DocumentBean bean : model.getDocuments()) {
			if (bean.getPk().equals(pk)) {
				model.setDocument(bean);
				model.setActiveIndexDocument(1); // element tab
			}
		}
		return toCampadmin();
	}

	public String toEditLocation(Integer pk) {
		model.setActiveIndex(0);
		for (LocationBean bean : model.getLocations()) {
			if (bean.getPk().equals(pk)) {
				model.setLocation(bean);
				model.setActiveIndexLocation(1);
			}
		}
		return toCampadmin();
	}

	public String toEditCamp(Integer pk) {
		model.setActiveIndex(1);
		for (CampBean bean : model.getCamps()) {
			if (bean.getPk().equals(pk)) {
				model.setCamp(bean);
				model.setActiveIndexCamp(1);
			}
		}
		return toCampadmin();
	}

	public String toEditCampDocuments(Integer pk) {
		FacesContext facesContext = FacesContext.getCurrentInstance();

		model.setActiveIndex(1);
		model.setActiveIndexCamp(2);
		model.loadCampDocuments(facesContext, pk);
		return "/pages/campadmin/edit.jsf";
	}

	public String doRemoveDocumentFromCamp(DocumentBean bean) {
		FacesContext facesContext = FacesContext.getCurrentInstance();

		model.removeDocumentFromCamp(facesContext, bean);
		return toEditCampDocuments(model.getCampPk());
	}

	public String doAddDocumentToCamp() {
		FacesContext facesContext = FacesContext.getCurrentInstance();

		model.addDocumentToCamp(facesContext);
		return toEditCampDocuments(model.getCampPk());
	}

	public String doLockSales() {
		FacesContext facesContext = FacesContext.getCurrentInstance();

		boolean result = model.lockSales(facesContext);
		if (result) {
			model.setCamps(new CampGateway(facesContext).getAllCampsFromTable());
		}
		return toEditCamp(model.getCamp().getPk());
	}

	public String doDeleteDocument() {
		FacesContext facesContext = FacesContext.getCurrentInstance();

		model.setActiveIndex(2);
		try {
			new DocumentGateway(facesContext).deleteDocument(model.getDocument().getPk());
			model.setActiveIndexDocument(0);
			model.setDocument(new DocumentBean(null));
		} catch (DataAccessException e) {
			facesContext.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "database error", e.getMessage()));
			LOGGER.error("AdminController.doDeleteDocument: ", e);
		}
		return toCampadmin();
	}

	public String doDeleteLocation() {
		FacesContext facesContext = FacesContext.getCurrentInstance();

		model.setActiveIndex(0);
		try {
			new LocationGateway(facesContext).deleteLocation(model.getLocation().getPk());
			model.setActiveIndexLocation(0);
			model.setLocation(new LocationBean(null));
		} catch (DataAccessException e) {
			facesContext.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "database error", e.getMessage()));
			LOGGER.error("AdminController.doDeleteLocation: ", e);
		}
		return toCampadmin();
	}

	public String doDeleteCamp() {
		FacesContext facesContext = FacesContext.getCurrentInstance();

		model.setActiveIndex(1);
		try {
			new CampGateway(facesContext).deleteCamp(facesContext, model.getCamp().getPk());
			model.setActiveIndexCamp(0);
			model.setCamp(new CampBean());
		} catch (DataAccessException e) {
			facesContext.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "database error", e.getMessage()));
			LOGGER.error("AdminController.doDeleteCamp: ", e);
		}
		return toCampadmin();
	}

	public String doDeleteCampprofile(Integer pk) {
		FacesContext facesContext = FacesContext.getCurrentInstance();

		model.setActiveIndex(3);
		try {
			Integer affected = new CampprofileGateway(facesContext).deleteCampprofile(pk);
			if (affected != 1) {
				facesContext.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_WARN, "database warning",
						"deleted " + affected + " database entries"));
			}
			model.setCampprofile(new CampprofileBean());
		} catch (DataAccessException e) {
			facesContext.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "database error", e.getMessage()));
			LOGGER.error("AdminController.doDeleteCampprofile: ", e);
		}
		return toCampadmin();
	}

	public String doAddCampprofile(Boolean validate) {
		isAdding = validate; // only for validation checks; if isAdding is false, the validate attributes in the faces input components are disabled
		FacesContext facesContext = FacesContext.getCurrentInstance();

		model.setActiveIndex(3);
		try {
			Integer affected = new CampprofileGateway(facesContext).add(model.getCampprofile());
			if (affected != 1) {
				facesContext.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_WARN, "database warning",
						"added " + affected + " database entries"));
			}
		} catch (DataAccessException e) {
			facesContext.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "database error", e.getMessage()));
			LOGGER.error("AdminController.doAddCampprofile: ", e);
		}
		return toCampadmin();
	}

	public String doUpsertDocument() {
		FacesContext facesContext = FacesContext.getCurrentInstance();

		model.setActiveIndex(2);
		try {
			model.getDocument().encodeUpload();
			new DocumentGateway(facesContext).upsert(model.getDocument());
			model.setActiveIndexDocument(0);
			model.setDocument(new DocumentBean(null));
		} catch (DataAccessException | IOException e) {
			facesContext.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "database error", e.getMessage()));
			LOGGER.error("AdminController.doUpsertDocument: ", e);
		}
		return toCampadmin();
	}

	public String doUpsertLocation() {
		FacesContext facesContext = FacesContext.getCurrentInstance();
		
		model.setActiveIndex(0);
		try {
			new LocationGateway(facesContext).upsert(model.getLocation());
			model.setActiveIndexLocation(0);
			model.setLocation(new LocationBean(null));
		} catch (DataAccessException e) {
			facesContext.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "database error", e.getMessage()));
			LOGGER.error("AdminController.doUpsertLocation: ", e);
		}
		return toCampadmin();
	}

	public String doUpsertCamp() {
		FacesContext facesContext = FacesContext.getCurrentInstance();

		model.setActiveIndex(1);
		try {
			new CampGateway(facesContext).upsert(model.getCamp());
			model.setActiveIndexCamp(0);
			model.setCamp(new CampBean());
		} catch (DataAccessException e) {
			facesContext.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "database error", e.getMessage()));
			LOGGER.error("AdminController.doUpsertCamp: ", e);
		}
		return toCampadmin();
	}

	public String doDownloadDocument(DocumentBean bean) {
		FacesContext facesContext = FacesContext.getCurrentInstance();

		model.setActiveIndex(2);
		model.setActiveIndexDocument(0);
		return super.doDownloadBase64(facesContext, bean.getDocument(), bean.getName(), bean.getFiletype().getLiteral());
	}

	public String doDownloadDocument(CampBean bean) {
		FacesContext facesContext = FacesContext.getCurrentInstance();

		model.setActiveIndex(1);
		model.setActiveIndexCamp(0);
		DocumentBean docBean = null;
		for (DocumentBean b : model.getDocuments()) {
			if (b.getPk().equals(bean.getFkDocument())) {
				docBean = b;
			}
		}
		if (docBean != null) {
			return super.doDownloadBase64(facesContext, docBean.getDocument(), docBean.getName(),
					docBean.getFiletype().getLiteral());
		} else {
			facesContext.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "error download document",

src/main/java/de/jottyfan/camporganizer/modules/campadmin/CampprofileBean.java
package de.jottyfan.camporganizer.modules.campadmin;

import java.util.Date;

/**
 * 
 * @author jotty
 *
 */
public class CampprofileBean {

	private Integer pk;
	private String forename;
	private String surname;
	private String campname;
	private Date startdate;
	private String module;
	private Integer fkProfile;
	private Integer fkCamp;

	/**
	 * get the full name of the person
	 * 
	 * @return forname + space + surname
	 */
	public String getFullname() {
		return new StringBuilder("").append(forename).append(" ").append(surname).toString();
	}

	public String getForename() {
		return forename;
	}

	public void setForename(String forename) {
		this.forename = forename;
	}

	public String getSurname() {
		return surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getCampname() {
		return campname;
	}

	public void setCampname(String campname) {
		this.campname = campname;
	}

	public Date getStartdate() {
		return startdate;
	}

	public void setStartdate(Date startdate) {
		this.startdate = startdate;
	}

	public String getModule() {
		return module;
	}

	public void setModule(String module) {
		this.module = module;
	}

	public Integer getPk() {
		return pk;
	}

	public void setPk(Integer pk) {
		this.pk = pk;
	}

	public Integer getFkProfile() {
		return fkProfile;
	}

	public void setFkProfile(Integer fkProfile) {
		this.fkProfile = fkProfile;
	}

	public Integer getFkCamp() {
		return fkCamp;
	}

	public void setFkCamp(Integer fkCamp) {
		this.fkCamp = fkCamp;
	}
}

src/main/java/de/jottyfan/camporganizer/modules/campadmin/DocumentBean.java
package de.jottyfan.camporganizer.modules.campadmin;

import java.io.IOException;
import java.io.InputStream;

import javax.servlet.http.Part;

import org.apache.commons.io.IOUtils;

import java.util.Base64;

import de.jottyfan.camporganizer.db.jooq.enums.EnumDocument;
import de.jottyfan.camporganizer.db.jooq.enums.EnumFiletype;

/**
 * 
 * @author jotty
 *
 */
public class DocumentBean {

	private final Integer pk;
	private EnumDocument doctype;
	private String name;
	private String document;
	private EnumFiletype filetype;
	private Part uploadfile;
	private String roles;

	public DocumentBean(Integer pk) {
		this.pk = pk;
	}

	public void encodeUpload() throws IOException {
		if (uploadfile != null) {
			InputStream inputStream = uploadfile.getInputStream();
			byte[] bytes = IOUtils.toByteArray(inputStream);
			if (bytes.length > 0) {
				document = Base64.getEncoder().encodeToString(bytes);
			} // not uploaded files should not be changed, so document must be kept as is
		}
	}

	public Integer getPk() {
		return pk;
	}

	public void setDoctype(EnumDocument doctype) {
		this.doctype = doctype;
	}

	public EnumDocument getDoctype() {
		return doctype;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getName() {
		return name;
	}

	public void setDocument(String document) {
		this.document = document;
	}

	public String getDocument() {
		return document;
	}

	public void setFiletype(EnumFiletype filetype) {
		this.filetype = filetype;
	}

	public EnumFiletype getFiletype() {
		return filetype;
	}

	public Part getUploadfile() {
		return uploadfile;
	}

	public void setUploadfile(Part uploadfile) {
		this.uploadfile = uploadfile;
	}

	public String getRoles() {
		return roles;
	}

	public void setRoles(String roles) {
		this.roles = roles;
	}
}

src/main/java/de/jottyfan/camporganizer/modules/campadmin/LocationBean.java
package de.jottyfan.camporganizer.modules.campadmin;

/**
 * 
 * @author jotty
 *
 */
public class LocationBean {
	private final Integer pk;
	private String name;
	private String url;
	private Integer fkDocument;

	public LocationBean(Integer pk) {
		super();
		this.pk = pk;
	}

	public String showUrl(int charAmount) {
		if (url == null) {
			return "";
		} if (url.trim().isEmpty()){
			return "";
		} else {
			int endIndex = charAmount > url.length() ? url.length() - 1 : charAmount;
			return url == null ? "" : url.substring(0, endIndex) + (endIndex < url.length() ? "…" : "");
		}
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public Integer getFkDocument() {
		return fkDocument;
	}

	public void setFkDocument(Integer fkDocument) {
		this.fkDocument = fkDocument;
	}

	public Integer getPk() {
		return pk;
	}
}

src/main/webapp/pages/campadmin/camp.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:f="http://xmlns.jcp.org/jsf/core" xmlns:h="http://xmlns.jcp.org/jsf/html"
  xmlns:b="http://bootsfaces.net/ui" xmlns:ui="http://java.sun.com/jsf/facelets">
<ui:composition>
  <b:tabView activeIndex="#{campadminModel.activeIndexCamp}">
    <b:tab title="Tabelle">
      <b:form>
        <b:dataTable value="#{campadminModel.camps}" var="c" lang="de" csv="true" pdf="true">
          <b:dataTableColumn label="Name">
            <b:commandButton action="#{campadminController.toEditCamp(c.pk)}" value="#{c.name}" look="link" />
          </b:dataTableColumn>
          <b:dataTableColumn label="Zeit" dataType="date" dataOrder="#{c.arrive}">
            <b:commandButton action="#{campadminController.toEditCamp(c.pk)}" value="#{c.campTime}" look="link" />
          </b:dataTableColumn>
          <b:dataTableColumn label="in">
            <b:commandButton action="#{campadminController.toEditCamp(c.pk)}" value="#{c.locationName}" look="link" />
          </b:dataTableColumn>
          <b:dataTableColumn label="Bestätigung">
            <b:commandButton action="#{campadminController.doDownloadDocument(c)}" value="" iconAwesome="download"
              rendered="#{c.fkDocument != null}" />
          </b:dataTableColumn>
          <b:dataTableColumn label="Dokumente">
            <b:commandButton action="#{campadminController.toEditCampDocuments(c.pk)}" value="verwalten" iconAwesome="doc" />
          </b:dataTableColumn>
          <b:dataTableColumn label="Anmeldungen">
            <h:outputText value="#{c.bookings}" />
          </b:dataTableColumn>
        </b:dataTable>
      </b:form>
    </b:tab>
    <b:tab title="Element">
      <b:form>
        <b:panelGrid colSpans="3,9" size="xs">
          <h:outputText value="ID = #{campadminModel.camp.pk}" />
          <b:commandButton action="#{campadminController.doResetCamp}" value="Felder leeren" />
          <h:outputText value="Name" />
          <b:inputText value="#{campadminModel.camp.name}" />
          <h:outputText value="von" />
          <b:datepicker value="#{campadminModel.camp.arrive}" />
          <h:outputText value="bis" />
          <b:datepicker value="#{campadminModel.camp.depart}" />
          <h:outputText value="Freizeitheim" />
          <b:selectOneMenu value="#{campadminModel.camp.fkLocation}">
            <f:selectItem itemValue="" itemLabel="--- bitte auswählen ---" />
            <f:selectItems value="#{campadminModel.locations}" var="l" itemValue="#{l.pk}" itemLabel="#{l.name}" />
          </b:selectOneMenu>
          <h:outputText value="Mindestalter" />
          <b:inputText value="#{campadminModel.camp.minAge}">
            <f:convertNumber integerOnly="true" />
          </b:inputText>
          <h:outputText value="Maximalalter" />
          <b:inputText value="#{campadminModel.camp.maxAge}">
            <f:convertNumber integerOnly="true" />
          </b:inputText>
          <h:outputText value="Preis" />
          <b:inputTextarea value="#{campadminModel.camp.price}" />
          <h:outputText value="Ferien in" />
          <b:inputText value="#{campadminModel.camp.countries}" tags="true" typeahead="true"
            typeaheadValues="#{campadminModel.possibleCountries}" />
          <h:outputText value="Bestätigung" />
          <b:selectOneMenu value="#{campadminModel.camp.fkDocument}" styleClass="filterdropdown">
            <f:selectItem itemValue="" itemLabel="--- bitte wählen ---" />
            <f:selectItems value="#{campadminModel.documents}" var="d" itemValue="#{d.pk}" itemLabel="#{d.name}" />
          </b:selectOneMenu>
          <h:outputText value="Verantwortlicher" />
          <b:selectOneMenu value="#{campadminModel.camp.fkProfile}" required="true"
            requiredMessage="Bitte das Feld Verantwortlicher ausfüllen.">
            <f:selectItem itemValue="" itemLabel="--- bitte wählen ---" />
            <f:selectItems value="#{campadminModel.profiles}" var="p" itemValue="#{p.pk}" itemLabel="#{p.fullname}" />
          </b:selectOneMenu>
          <h:outputText value="Kassenschluss" rendered="#{!campadminModel.camp.lockSales}" />
          <b:dropButton value="Rechnungen abschließen" iconAwesome="lock" look="warning"
            rendered="#{!campadminModel.camp.lockSales}">
            <b:commandButton action="#{campadminController.doLockSales}" value="ja, endgültig Rechnungen festschreiben"
              look="warning" />
          </b:dropButton>
          <b:dropButton value="löschen" iconAwesome="trash-o" look="danger">
            <b:commandButton action="#{campadminController.doDeleteCamp}" value="ja, unwiederbringlich löschen" look="danger" />
          </b:dropButton>
          <b:commandButton action="#{campadminController.doUpsertCamp}" value="Übernehmen" look="primary" />
        </b:panelGrid>
      </b:form>
    </b:tab>
    <b:tab title="Dokumente">
      <b:form rendered="#{campadminModel.campPk != null}">
        <b:alert severity="info">Freizeit <h:outputText value="#{campadminModel.campPk}" />
        </b:alert>
        <b:dataTable value="#{campadminModel.campDocuments}" var="d">
          <b:dataTableColumn label="Name">
            <b:commandButton action="#{campadminController.toEditDocument(d.pk)}" value="#{d.name}" look="link" />
          </b:dataTableColumn>
          <b:dataTableColumn label="Aktionen">
            <b:commandButton action="#{campadminController.doDownloadDocument(d)}" value="" iconAwesome="download" />
            <b:commandButton action="#{campadminController.doRemoveDocumentFromCamp(d)}" value="" iconAwesome="trash"
              look="danger" style="margin-left: 32px" />
          </b:dataTableColumn>
        </b:dataTable>
        <b:alert severity="info">Es können nur Dokumente verwendet werden, die den Dokumententyp camp haben.</b:alert>
        <b:panelGrid colSpans="9,3" size="xs">
          <b:selectOneMenu value="#{campadminModel.documentPk}" styleClass="filterdropdown">
            <f:selectItems value="#{campadminModel.noncampDocuments}" var="d" itemValue="#{d.pk}"
              itemLabel="#{d.name} #{d.filetype.literal}" />
          </b:selectOneMenu>
          <b:commandButton action="#{campadminController.doAddDocumentToCamp}" value="hinzufügen" look="success" />
        </b:panelGrid>
      </b:form>
      <b:alert severity="info" rendered="#{campadminModel.campPk == null}">Bitte über Reiter Tabelle -> Dokumente -> verwalten eine Freizeit auswählen!</b:alert>
    </b:tab>
  </b:tabView>
</ui:composition>
</html>

src/main/webapp/pages/campadmin/edit.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html" xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core" xmlns:b="http://bootsfaces.net/ui">
<h:body>
	<ui:composition template="/pages/template.xhtml">
		<ui:define name="content">
			<b:panel rendered="#{profileBean.hasRole('campadmin')}" title="Freizeitadministration" collapsible="false">
				<b:alert severity="info" closable="true">
					<h:outputText value="Der RSS-Feed des Freizeitadministrators lautet: " />
					<b:navLink href="https://www.onkelwernerfreizeiten.de/camporganizer/rss.jsf?recipientCode=campadmin" target="#"
						value="https://www.onkelwernerfreizeiten.de/camporganizer/rss.jsf?recipientCode=campadmin" iconAwesome="rss" />
				</b:alert>
				<b:tabView activeIndex="#{campadminModel.activeIndex}">
					<b:tab title="Freizeitheime" styleClass="dist16">
						<ui:include src="location.xhtml" />
					</b:tab>
					<b:tab title="Freizeiten" styleClass="dist16">
						<ui:include src="camp.xhtml" />
					</b:tab>
					<b:tab title="Dokumente" styleClass="dist16">
						<ui:include src="document.xhtml" />
					</b:tab>
					<b:tab title="Mitarbeiter" styleClass="dist16">
						<ui:include src="campprofile.xhtml" />
					</b:tab>
				</b:tabView>
			</b:panel>
		</ui:define>
	</ui:composition>
</h:body>
</html>